version: '3'
tasks:
  asm:
    cmds:
      - for: ['test', 'test1']
        cmd: nasm -f win32 {{ .ITEM }}.asm -o {{ .ITEM }}.obj -Wall
      - cmd: GoLink.exe /console /entry _start {{ .ITEM }}.obj kernel32.dll
        for: ['test', 'test1']