[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../models" }
bincode = "1.3.3"
ws = "0.9.2"
ctrlc = "3.2.2"
clap = "4"
